execute:
  freeze: auto

project:
  type: website
  output-dir: docs

# Enable brand integration across the project
brand: "_brand.yml"

# Default format configuration
format:
  jdc-revealjs:
    # Brand integration will automatically apply colors, fonts, and logos
    embed-resources: true
