on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish (RevealJS)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides.qmd

      - name: Install TinyTeX (PDF)
        run: quarto install tinytex

      - name: Render and Publish (PDF)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: report.qmd

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
